#!/bin/bash

#paths to solvers
pyglaf="solvers/pyglaf/pyglaf.py"
ArgSemSAT="solvers/ArgSemSATS/ArgSemSAT"

#mapping of benchmark frameworks to tasks
declare -a A=("DS-PR" "EE-PR" "EE-CO")
declare -a B=("DS-ST" "DC-ST" "SE-ST" "EE-ST" "DC-PR" "SE-PR" "DC-CO")



for task in "${A[@]}"
do	
	start_time=`date +%s`
	$pyglaf -f ~/A/1/sembuster_150.tgf -p task -fo tgf
	end_time=`date +%s`
	echo execution time was `expr $end_time - $start_time` s.
done
